export enum interviewsActionTypes {
  LOADING = 'LOADING_INTERVIEWS',
  LOADED = 'LOADED_INTERVIEWS',
  SET_LIST = 'SET_INTERVIEWS_LIST',
  ADD = 'ADD_INTERVIEW',
  DELETE = 'DELETE_INTERVIEW',
  DELETE_MULTIPLE = 'DELETE_MULTIPLE_INTERVIEWS',
  UPDATE = 'UPDATE_INTERVIEW',
}
