import { IInterviewModel } from './interfaces';

export const dummyInterviews: IInterviewModel[] = [
  {
    id: 1,
    title: 'Senior Software Engineer Interview',
    candidateName: 'Anuj Parikh',
    templateId: 2,
    questionIds: [],
    categoryIds: [],
    duration: 60,
    dateTime: '15 Jan - 01:00 PM',
    role: 'Senior Software Engineer',
    overallFeedback: true,
  },
  {
    id: 2,
    title: 'Software Engineer Interview',
    candidateName: 'Palak Parikh',
    templateId: 1,
    questionIds: [],
    categoryIds: [],
    duration: 45,
    dateTime: '16 Jan - 01:00 PM',
    role: 'Software Engineer',
  },
  {
    id: 3,
    title: 'Intern Interview',
    candidateName: 'Arya Parikh',
    questionIds: [],
    categoryIds: [],
    duration: 30,
    dateTime: '15 Jan - 01:00 PM',
    role: 'Internship',
    overallFeedback: true,
  },
  {
    id: 1,
    title: 'Senior Software Engineer Interview',
    candidateName: 'Anuj Parikh - 2',
    templateId: 2,
    questionIds: [],
    categoryIds: [],
    duration: 60,
    dateTime: '15 Jan - 01:00 PM',
    role: 'Senior Software Engineer',
  },
  {
    id: 2,
    title: 'Senior Software Engineer Interview',
    candidateName: 'Palak Parikh - 2',
    templateId: 1,
    questionIds: [],
    categoryIds: [],
    duration: 45,
    dateTime: '16 Jan - 01:00 PM',
    role: 'Senior Software Engineer',
    overallFeedback: true,
  },
  {
    id: 3,
    title: 'Intern Interview',
    candidateName: 'Arya Parikh - 2',
    questionIds: [],
    categoryIds: [],
    duration: 30,
    dateTime: '15 Jan - 01:00 PM',
    role: 'Internship',
  },
];
