export const categories = [
  { name: 'Full Stack', no: 10 },
  { name: 'DevOps', no: 15 },
  { name: 'Backend', no: 13 },
  { name: 'Frontend', no: 20 },
  { name: 'React', no: 21 },
  { name: 'Angular', no: 5 },
  { name: 'Javascript', no: 80 },
  { name: 'AWS', no: 25 },
  { name: 'Leadership', no: 10 },
  { name: 'Testing', no: 15 },
  { name: 'Microservices', no: 10 },
  { name: 'Architechure', no: 10 },
  { name: 'UX', no: 10 },
  { name: 'Java', no: 10 },
  { name: 'Springboot', no: 10 },
  { name: 'Selenium', no: 10 },
  { name: 'Databases', no: 10 },
  { name: 'Kafka', no: 10 },
  { name: 'Algorithms', no: 10 },
  { name: 'Datastructures', no: 10 },
];
