import { IQuestionModel, DifficultyLevels } from './interfaces';

export const dummyQuestions: IQuestionModel[] = [
  {
    id: 1,
    key: Math.random() * 100,
    title: 'Operations on DS',
    question: 'What are the various operations that can be performed on different Data Structures?',
    categories: ['Datastructures', 'Algorithms'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 2,
    key: Math.random() * 100,
    title: 'Array vs LL',
    question: 'How is an Array different from Linked List?',
    categories: ['Datastructures', 'Algorithms'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 3,
    key: Math.random() * 100,
    title: 'Stack',
    question: 'What is Stack and where it can be used?',
    categories: ['Datastructures', 'Algorithms'],
    difficultyLevel: DifficultyLevels.Medium,
    frequency: 8,
  },
  {
    id: 4,
    key: Math.random() * 100,
    title: 'Queue and Queue vs Stack',
    question:
      'What is a Queue, how it is different from stack and how is it implemented? Can we do the Queue implementation with Java?',
    categories: ['Datastructures', 'Algorithms'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 5,
    key: Math.random() * 100,
    title: 'BFS and DFS graph',
    question: 'Which data structures are used for BFS and DFS of a graph?',
    categories: ['Datastructures', 'Algorithms'],
    difficultyLevel: DifficultyLevels.Medium,
    frequency: 8,
  },
  {
    id: 6,
    key: Math.random() * 100,
    title: 'Real vs Virtual DOM',
    question: 'Difference between Real DOM and Virtual DOM?',
    categories: ['React', 'Javascript'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
  {
    id: 7,
    key: Math.random() * 100,
    title: 'React features',
    question: 'What are latest feature of React?',
    categories: ['React', 'Javascript'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 8,
    key: Math.random() * 100,
    title: 'React vs Angular',
    question: 'How is React different from Angular?',
    categories: ['Angular', 'Javascript', 'Frontend'],
    frequency: 8,
    difficultyLevel: DifficultyLevels.Hard,
  },
  {
    id: 9,
    key: Math.random() * 100,
    title: 'Everything is component',
    question: 'What do you understand from “In React, everything is a component"?',
    categories: ['React', 'Javascript'],
    difficultyLevel: DifficultyLevels.Medium,
    frequency: 8,
  },
  {
    id: 10,
    key: Math.random() * 100,
    title: 'Stateful vs stateless',
    question: 'Differentiate between stateful and stateless components?',
    categories: ['Javascript'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
  {
    id: 11,
    key: Math.random() * 100,
    title: '== vs equals(..)',
    question:
      'What is the difference between “==” and “equals(…)” in comparing Java String objects?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 12,
    key: Math.random() * 100,
    title: 'Strings java',
    question: 'Can you explain how Strings are interned in Java?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Medium,
    frequency: 8,
  },
  {
    id: 13,
    key: Math.random() * 100,
    title: 'Explain Java code',
    question:
      'Can you describe what the following code does and what parts of memory the local variables, objects, and references to the objects occupy in Java?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
  {
    id: 14,
    key: Math.random() * 100,
    title: 'Overriding and Polymorphism',
    question: 'Are overriding & polymorphism applicable to static methods as well?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
  {
    id: 15,
    key: Math.random() * 100,
    title: 'Static vs Dynamic class',
    question: 'Explain static vs. dynamic class loading?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Medium,
    frequency: 8,
  },
  {
    id: 16,
    key: Math.random() * 100,
    title: '== vs equals(..)',
    question:
      'What is the difference between “==” and “equals(…)” in comparing Java String objects?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 17,
    key: Math.random() * 100,
    title: 'Strings java',
    question: 'Can you explain how Strings are interned in Java?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
  {
    id: 18,
    key: Math.random() * 100,
    title: 'Explain Java code',
    question:
      'Can you describe what the following code does and what parts of memory the local variables, objects, and references to the objects occupy in Java?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Easy,
    frequency: 8,
  },
  {
    id: 19,
    key: Math.random() * 100,
    title: 'Overriding and Polymorphism',
    question: 'Are overriding & polymorphism applicable to static methods as well?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
  {
    id: 20,
    key: Math.random() * 100,
    title: 'Static vs Dynamic class',
    question: 'Explain static vs. dynamic class loading?',
    categories: ['Java'],
    difficultyLevel: DifficultyLevels.Hard,
    frequency: 8,
  },
];
