export enum templatesActionTypes {
  LOADING = 'LOADING_TEMPLATES',
  LOADED = 'LOADED_TEMPLATES',
  SET_LIST = 'SET_TEMPLATES_LIST',
  DELETE = 'DELETE_TEMPLATE',
  DELETE_MULTIPLE = 'DELETE_MULTIPLE_TEMPLATES',
  UPDATE = 'UPDATE_TEMPLATE',
}
