import { ITemplateModel } from './interfaces';
import { v4 as uuid } from 'uuid';

export const dummyTemplates: ITemplateModel[] = [
  {
    id: uuid(),
    title: 'Senior Software Engineer',
    description: 'Template for senior software engineer',
    categories: ['Architecture', 'Frontend', 'Backend'],
    duration: 60,
    roles: ['Senior Software Engineer'],
    questions: [],
    interviews: [],
  },
  {
    id: uuid(),
    title: 'Software Engineer',
    description: 'Template for software engineer',
    categories: ['Frontend', 'Backend'],
    duration: 60,
    roles: ['Software Engineer'],
    questions: [],
    interviews: [],
  },
  {
    id: uuid(),
    title: 'Technology Lead',
    description: 'Template for technology lead',
    categories: ['Architecture', 'Frontend', 'Backend', 'DevOps'],
    duration: 90,
    roles: ['Technology Lead'],
    questions: [],
    interviews: [],
  },
  {
    id: uuid(),
    title: 'SSE (telephonic)',
    description: 'Template for senior software engineer telephonic interview',
    categories: ['Frontend', 'Backend'],
    duration: 45,
    roles: ['Senior Software Engineer'],
    questions: [],
    interviews: [],
  },
  {
    id: uuid(),
    title: 'Software Engineer in Test',
    description: 'Template for test software engineer ',
    categories: ['Testing', 'Frontend', 'Selenium', 'Java'],
    duration: 45,
    roles: ['Software Engineer in Test'],
    questions: [],
    interviews: [],
  },
  {
    id: uuid(),
    title: 'User Experience (UX)',
    description: 'Template for User experience interview',
    categories: ['UX', 'Design'],
    duration: 60,
    roles: ['User Experience'],
    questions: [],
    interviews: [],
  },
];
