export default [
  {
    type: 'upcoming',
    title: 'Upcoming Interviews',
    data: [
      {
        key: '1',
        name: 'Anuj Parikh',
        role: 'Software Engineer',
        dateTime: '15 Jan - 01:00 PM',
        duration: '1hr',
        noOfCategories: 3,
      },
      {
        key: '2',
        name: 'Palak Parikh',
        role: 'Senior Software Engineer',
        dateTime: '15 Jan - 09:00 AM',
        duration: '1.5hr',
        noOfCategories: 5,
      },
      {
        key: '3',
        name: 'Arya Parikh',
        role: 'Engineering Manager',
        dateTime: '15 Jan - 03:00 PM',
        duration: '1hr',
        noOfCategories: 4,
      },
      {
        key: '4',
        name: 'Anuj Parikh',
        role: 'Software Engineer',
        dateTime: '15 Jan - 01:00 PM',
        duration: '1hr',
        noOfCategories: 3,
      },
      {
        key: '5',
        name: 'Palak Parikh',
        role: 'Senior Software Engineer',
        dateTime: '16 Jan - 09:00 AM',
        duration: '1.5hr',
        noOfCategories: 5,
      },
    ],
  },
  {
    type: 'pending',
    title: 'Pending Feedback',
    data: [
      {
        key: '1',
        name: 'Anuj Parikh',
        role: 'Software Engineer',
        dateTime: '15 Jan - 01:00 PM',
        feedback: true,
      },
      {
        key: '2',
        name: 'Palak Parikh',
        role: 'Senior Software Engineer',
        dateTime: '15 Jan - 09:00 AM',
        feedback: false,
      },
      {
        key: '3',
        name: 'Arya Parikh',
        role: 'Engineering Manager',
        dateTime: '15 Jan - 03:00 PM',
        feedback: true,
      },
      {
        key: '4',
        name: 'Palak Parikh',
        role: 'Senior Software Engineer',
        dateTime: '15 Jan - 09:00 AM',
        feedback: false,
      },
      {
        key: '5',
        name: 'Arya Parikh',
        role: 'Engineering Manager',
        dateTime: '15 Jan - 03:00 PM',
        feedback: true,
      },
    ],
  },
];
