export const roleTypes = ['Software Engineer', 'Tech Lead', 'QA', 'Senior Software Engineer'];
export const categoryTypes = ['Full Stack', 'DevOps', 'Backend', 'Frontend'];
export type templateDataType = {
  id: number;
  title: string;
  duration: string;
  categories: string[];
  noOfQuestions: number;
  lastUpdateAt: string;
  usedForInterviews: number;
  associatedRoles: string[];
};
export const templateData = [
  {
    id: 1,
    title: 'SSE (in person)',
    duration: '1hr',
    categories: ['Full Stack', 'Frontend'],
    noOfQuestions: 34,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 8,
    associatedRoles: ['Senior Software Engineer'],
  },
  {
    id: 2,
    title: 'SE (in person)',
    duration: '45mins',
    categories: ['Backend'],
    noOfQuestions: 25,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 5,
    associatedRoles: ['Software Engineer'],
  },
  {
    id: 3,
    title: 'SE (telephonic)',
    duration: '45mins',
    categories: ['React', 'Frontend'],
    noOfQuestions: 30,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 2,
    associatedRoles: ['Software Engineer'],
  },
  {
    id: 4,
    title: 'SSE (in person)',
    duration: '1hr',
    categories: ['Backend'],
    noOfQuestions: 40,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 1,
    associatedRoles: ['Senior Software Engineer'],
  },
  {
    id: 5,
    title: 'Tech Lead (in person)',
    duration: '1.5hr',
    categories: ['Architecture', 'Algorithm'],
    noOfQuestions: 15,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 2,
    associatedRoles: ['Technology Lead'],
  },
  {
    id: 6,
    title: 'Engineer Manager',
    duration: '1hr',
    categories: ['Full Stack', 'Management'],
    noOfQuestions: 15,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 2,
    associatedRoles: ['Engineer Manager'],
  },
  {
    id: 7,
    title: 'DevOps (in person)',
    duration: '1hr',
    categories: ['AWS', 'Cloud', 'Services'],
    noOfQuestions: 20,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 4,
    associatedRoles: ['Cloud Engineer'],
  },
  {
    id: 8,
    title: 'SSE (in person)',
    duration: '1hr',
    categories: ['Full Stack', 'Frontend'],
    noOfQuestions: 34,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 8,
    associatedRoles: ['Senior Software Engineer'],
  },
  {
    id: 9,
    title: 'SE (in person)',
    duration: '45mins',
    categories: ['Backend'],
    noOfQuestions: 25,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 5,
    associatedRoles: ['Software Engineer'],
  },
  {
    id: 10,
    title: 'SE (telephonic)',
    duration: '45mins',
    categories: ['React', 'Frontend'],
    noOfQuestions: 30,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 2,
    associatedRoles: ['Software Engineer'],
  },
  {
    id: 11,
    title: 'SSE (in person)',
    duration: '1hr',
    categories: ['Backend'],
    noOfQuestions: 40,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 1,
    associatedRoles: ['Senior Software Engineer'],
  },
  {
    id: 12,
    title: 'Tech Lead (in person)',
    duration: '1.5hr',
    categories: ['Architecture', 'Algorithm'],
    noOfQuestions: 15,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 2,
    associatedRoles: ['Technology Lead'],
  },
  {
    id: 13,
    title: 'Engineer Manager',
    duration: '1hr',
    categories: ['Full Stack', 'Management'],
    noOfQuestions: 15,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 2,
    associatedRoles: ['Engineer Manager'],
  },
  {
    id: 14,
    title: 'DevOps (in person)',
    duration: '1hr',
    categories: ['AWS', 'Cloud', 'Services'],
    noOfQuestions: 20,
    lastUpdateAt: Date.now().toString(),
    usedForInterviews: 4,
    associatedRoles: ['Cloud Engineer'],
  },
];
